# Generated by Django 5.1 on 2024-08-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_birth_date_customer_birth_of_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='Order',
        ),
    ]
