# Generated by Django 5.1 on 2024-08-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_order_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='Zip_code',
        ),
    ]
