# Generated by Django 5.1 on 2024-08-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_birth_of_date_customer_birth_of_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Birth_of_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='membership',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
