# Generated by Django 5.1 on 2024-08-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
