# Generated by Django 5.1 on 2024-08-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='last_updated',
        ),
    ]
