# Generated by Django 5.1 on 2024-08-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_category_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_status',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='placed_at',
            new_name='date_order',
        ),
        migrations.AddField(
            model_name='product',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
